name: Linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install modules
        run: npm install

      - name: Build Project
        run: npm run build:prod
        if: always()

      - name: Code linting
        run: npm run lint:ts
        if: always()

      - name: Styles linting
        run: npm run lint:css
        if: always()

      - name: Unit testing
        run: npm run test:unit
        if: always()

      - name: Build storybook
        run: npm run storybook:build
        if: always()

      - name: Screenshot testing
        run: npm run test:ui:ci:tempfix
        if: always()
